[[abseil_cpp]]
arch = "aarch64"
git-tree-sha1 = "d91fff31ccbcfa6efc5c57de66dba36937d057b7"
os = "macos"

    [[abseil_cpp.download]]
    sha256 = "52ac77beea01a2dcca3e0b3d2a057eaaee2d5435be89a2ff80ad5ddd08fe71b5"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.aarch64-apple-darwin.tar.gz"
[[abseil_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ce94eb047e5cb122f5c3a87380accc149aa7de3"
libc = "glibc"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "42edce5302b2218504edf62a2ea55d28c556b6d54124f987157918305d00e9f3"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[abseil_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff9e4df60fe941ddf957fc7f53c175b0143ca3d1"
libc = "glibc"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "c8f7cbd10adbb0ec12dcc6057c4cbf12b0aaa7a7ded8b43e0183a58a6690ed04"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[abseil_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bbf638ebd53097d07f376a3c5c4297301c6c21ce"
libc = "musl"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "7c7a144c5ab2688ff2e6c921fbca063e84309f35518c17f95430b733c18826a3"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[abseil_cpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "334efb1fa5ebeffaf5fea2b34d814afb7f1fd2b2"
libc = "musl"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "ca0de8b850667179dd75c0091db4580fdb6fcab6aa11639e495df99f117c7ed6"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[abseil_cpp]]
arch = "aarch64"
git-tree-sha1 = "d1ee63e1d89eb621ac7078d125c1dc3a89a0a522"
os = "freebsd"

    [[abseil_cpp.download]]
    sha256 = "ec8321549223aae1f2fd61db2abd3283496d4498fa7f9bb86ccfd3656a9eccb1"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.aarch64-unknown-freebsd.tar.gz"
[[abseil_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a473cbeefcff5a740226fcc0b0360577ff4ae790"
libc = "glibc"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "cf396f0c5e9cb1aca5a77200a9dfe37a373d0d68ab0b404564e4ad41242d00f7"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[abseil_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6eff2eafbe61036022cd3003d31bb8168b1dd1ab"
libc = "glibc"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "51dc725d8c4e83f1ee5b2788b843c79831674ab7c78fda5906086a6ac63a92f4"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[abseil_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "091a9025b2e5dcad04c96db37da9bcd7bcbb8663"
libc = "musl"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "486e3232270bb89b89a2aa3eeec1c25e630d4341a49fd194c8c45068350df582"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[abseil_cpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d7fd47c8ef8ac5bd965e2b0eb9d8d0ea175ff5d"
libc = "musl"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "710a51e4635feb9cb0fd2ff7f948219d6aca8efeea41ff1a5cf03f14a6d59254"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[abseil_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd86788faa985edd84496427366d222c3dc2bd4d"
libc = "glibc"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "7890f81929f9a8a8f839497bd3fd09761cdf12ebfbefd53cb9190a0c37703be8"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[abseil_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bafa71f4bde464f094254d72427b5ded1f867c30"
libc = "glibc"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "53465894e2d868ae6394ccf2b3aad03e0744f8441a0c10ea87791e1f934e863c"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[abseil_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a509d1414e5edc84e7ee7e82facb3b22b94261d2"
libc = "musl"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "75ca3122b79f88ceb1dabc1e354dccb91fb8a06584d6b1d51bbe1d050e1c0910"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[abseil_cpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16efd556413cfbe9102292b7a9b7404d77a32f74"
libc = "musl"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "b30403531a21dd9bcf08980266a37316ec03cb2dd5a986df736726779c7ffb8b"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[abseil_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0595a952e3ba29c3fec47e16fe66e02c5865841a"
libc = "glibc"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "e251e80a5d8c0f17be860b871272a93ef094c41624176bbd94cdd00a86fe5cb6"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.i686-linux-gnu-cxx03.tar.gz"
[[abseil_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81ef44af3764fadaf5498b8d21d625a533ca69a1"
libc = "glibc"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "c85ac9d15c65d0185b29158d389a7fdd91f9f8ed1175ba7827c1b7d4b2d672b3"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.i686-linux-gnu-cxx11.tar.gz"
[[abseil_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d3afcffc63a66f33cd2ab208e8f199ba9d53a98a"
libc = "musl"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "2c8a35e83e6eafaffe5a0d4139cce405c1e6390271e2d6b0d186123857290f7b"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.i686-linux-musl-cxx03.tar.gz"
[[abseil_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bb566c12f10d50dfa3f4d696cd62f3635c28a32"
libc = "musl"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "6143da01bb40c1096ed81f0c375694bdbdbc49444b377b0147436b5d756bed95"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.i686-linux-musl-cxx11.tar.gz"
[[abseil_cpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a36d2695cdb8cc11c98cce7011262c8abad5b5ac"
os = "windows"

    [[abseil_cpp.download]]
    sha256 = "c1192fa97417b5bfa054d6e204f828a76453262507df8674b2df5abf2d32fa7e"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[abseil_cpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56f055ab22f2cbd060c61d8ce8189ddcecbcdb41"
os = "windows"

    [[abseil_cpp.download]]
    sha256 = "add6381c2497a292f73781fb836ddbbb29f9c064b39f5a8274dbd6f5bd1ab8e8"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[abseil_cpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a50430917d1cb1fc429ffafcb165352465563fa5"
libc = "glibc"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "4fac2465e4d816c68cc49f87528a21b606468ebde3f0d5cd2eec1be54fef7302"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[abseil_cpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5dd1780826bcd14446bb06b4225261a6c9cd0be0"
libc = "glibc"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "ce8fb44fe41dd51b6598e6b0f961f204e58a076d2fe43e25371170034c8cee83"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[abseil_cpp]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99e222f6c8bed6fa54c01ed92a973cde93199954"
libc = "glibc"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "8b272c903ad5c058a525111de396b2e82118c11d9fb620cc25bbf2abd43c1f33"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.riscv64-linux-gnu-cxx03.tar.gz"
[[abseil_cpp]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "566439996957890618fd77478dcb64647a33415d"
libc = "glibc"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "bf99c8d3d4ac74a1229edde1411b6be29c8f166358c8e9af2a4ce0e020a39047"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[abseil_cpp]]
arch = "x86_64"
git-tree-sha1 = "14c8ee86a87b9e48b9c6d4dc567275a536edad0e"
os = "macos"

    [[abseil_cpp.download]]
    sha256 = "638e4c82ec75fd0514e7e72652ba8cb72c807a6d042bf679ee7b7c653dd99470"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.x86_64-apple-darwin.tar.gz"
[[abseil_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6f967714aec1c4de08d06d1ae55f8856f882fcf"
libc = "glibc"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "165cb517fc3942ada3b406909c1c508fd41ddc8f598a19ff6cddaa4275366628"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[abseil_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "894e636de924c5608adc50cf968ac71c63754c54"
libc = "glibc"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "2333ffdaad379d4d75fa283927aedffff6ec8e2814e52bee7d12c3355019ba43"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[abseil_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c148055cc07bfd2ed5ec9cebf2a149b2f76c128b"
libc = "musl"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "7bef58e23247247f70d47271b829ec266346e1aa23c07e7cc3cc90920e5db7c2"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[abseil_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3538d0082f7ce3b378ec69085726a8a5e583595"
libc = "musl"
os = "linux"

    [[abseil_cpp.download]]
    sha256 = "cf7090ebe0af349425e7ab0c43b37f345a238e7412e64838c30fe262939076c2"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[abseil_cpp]]
arch = "x86_64"
git-tree-sha1 = "8132e54a0a7a2e29e985db0699d38fdc3ed15968"
os = "freebsd"

    [[abseil_cpp.download]]
    sha256 = "4bf1c15fd0152f9994c83b5f00c553940a7d05b2fc1b0830717ae3043919de28"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.x86_64-unknown-freebsd.tar.gz"
[[abseil_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e0b283348f27ba5e1384824870f7f17d5ca3d8a"
os = "windows"

    [[abseil_cpp.download]]
    sha256 = "44dc0cad87840fcf3559c50a19353c2422dcdcf7dff0a7064b8e985cc347612c"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[abseil_cpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2dfaba6aea77710d6d9b81f549511fc7b5d84d71"
os = "windows"

    [[abseil_cpp.download]]
    sha256 = "5561159c61d112848e2126edc83fa09b2d3e7388f4ef9f2d7dc11eaca35d552d"
    url = "https://github.com/JuliaBinaryWrappers/abseil_cpp_jll.jl/releases/download/abseil_cpp-v20230125.0.0+0/abseil_cpp.v20230125.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
